nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Changez l'origine selon votre application
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Link']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/': # Appliquer les règles aux routes qui commencent par /api/
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      expose_headers: ['Link']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      max_age: 3600
